config/routes.rb
Rails.application.routes.draw do

  resources :employees, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :users do   
      resources :unavailabilities   
  end
  resources :schedules, only: [:index, :show, :new, :create]

  resources :shifts, only: [:create]

  get 'schedule/:id' => 'schedules#show'

  root 'users#index'

  get ':id/new' => 'companies#new_employee', as: "new_employee"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :shifts
  has_many :users, through: :shifts
  belongs_to :location
  



end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :require_login, :only => [:new, :index]

  def index
    @schedules = Schedule.last(5)
  end


  def show
    @schedule_day_formatted = Date.iso8601(params[:id])
    @schedule = Schedule.where("week_of = ?", @schedule_day_formatted).first
    @shifts = @schedule.shifts

    @last_week = fetch_schedule(@schedule_day_formatted, -1)
    @next_week = fetch_schedule(@schedule_day_formatted, 1)


    @location = @schedule.location

    @earliest_open = @location.company.earliest_open(@location).floor
    @latest_close = @location.company.latest_close(@location).ceil
  end

  def new
    @shifts = []
    @company = current_user.company
    @locations = @company.locations
    @location = @company.locations.first
    @earliest_open = @company.earliest_open(@location)
    @latest_close = @company.latest_close(@location)

  end

  def create

    # Organize and separate our data
    scheduleData = params['schedule']['0']
    shiftData = []

    shiftIDs = []

    for i in (1...params['schedule'].length)
      shiftData << params['schedule'][i.to_s]
    end

    # Either find or create a schedule with our schedule params
    @schedule = Schedule.create!(schedule_params)

    shiftData.each do |shift|
      @shift = @schedule.shifts.new

      day = @schedule.week_of + shift["day"].to_i
      @shift.start_time = day.to_time + ( shift["start"].to_f * 3600 ).to_i
      @shift.end_time = day.to_time + ( shift["end"].to_f * 3600 ).to_i

      @shift.save

      shift["database_id"] = @shift.id

    end

    respond_to do |format|
      format.json { render :json => { shifts: shiftData } }
    end


  end

  private

  def schedule_params
    params.require(:schedule).require(:"0").permit(:week_of, :location_id)
  end

  def current_week_number(date, backWeeks=0)
    t = date + (7*backWeeks)
    return t.cweek
  end

  def fetch_schedule(schedule_date, offset)
    week = current_week_number(schedule_date, offset)
    scheduleDate = Date.commercial(Date.today.year, week)
    schedule = Schedule.where("week_of = ?", scheduleDate).last

    return schedule if schedule
    return nil
  end


  # def shift_params(n)
  #   params.require(:schedule).require(n.to_sym).permit(:)
  # end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  HOURHEIGHT = 50
  MORNINGOFFSET = 1 * HOURHEIGHT

  ### NOTES ON SHIFT PLACEMENT. 
  # There are 3 important variables for positioning each shift: 
  #  - Day of the week (distance from left)   
  #  - Hour of the day (distance from top) 
  #  - Length of shift (height) 

  def businessClosedClassAdd(location, day, time, onthehour)
    open = location[day.downcase+"_open"].hour
    close = location[day.downcase+"_close"].hour

    if location[day.downcase+"_open"].min != 0
      open += 0.5
    end
    
    if location[day.downcase+"_close"].min != 0
      close += 0.5
    end
    


    return "background: #DDD; border: 0px" if ( open > time || close <= time ) 

    
  end

  def getDateOffset(s)
    (s.start_time.day - @schedule.week_of.day).to_i
  end

  def getTimeOffset(s)
    ((s.start_time.hour + ( s.start_time.min / 60.0 ) ) - (@earliest_open) )
  end

  def getShiftHeight(s)
    (s.end_time - s.start_time) / 3600
  end


  def printTime(time)
    time >= 12 ? timeLabel = 'PM' : timeLabel = 'AM'
    time -= 12 if time > 12

    "<div class='hour_label'>#{time}:00 <span class='am_pm_label'>#{timeLabel}</span> -</div>".html_safe
  end

  def printTimeFloat(time)
    if time.min != 0
      return time.hour + 0.5
    else
      return time.hour
    end
  end
  
end

app/views/schedules/_schedule.html.erb
  <div id="new_schedule_container" style="font-size: 0.8em">
    <% @weekdays.each_with_index do |day, index| %><!--
  --><div class="day" id="day_<%= index+1 %>">
      <div class="day_label"><%= day %></div>
      <% for i in (@earliest_open.floor...@latest_close.ceil) do %>
        <% if index == 0 && i >= @earliest_open.floor %>
          <%= printTime(i) %>
        <% end %>

        <div class="hour" style="height: 15px;<%= businessClosedClassAdd(@location, day, i, true) %>"></div>
        <div class="halfhour" style="height: 15px;<%= businessClosedClassAdd(@location, day, (i+0.5), false) %>"></div>
      <% end %>
    </div><!--
  <% end %>
  --><div id="generated_shifts_container">
      <% @shifts.each do |s| %>
        <% @date_offset = getDateOffset(s) %>
        <% @time_offset = getTimeOffset(s) %>
        <% @shift_height = getShiftHeight(s) %>
        <div class="new_shift" id="shift_<%= s.id %>" data-weekday="<%= @date_offset %>" data-start-time="<%= @time_offset %>" data-shift-length="<%= @shift_height %>"><div class="filler"><% s.users.each do |u| %><div class="employee_avatar_clone" id="employee_<%= u.id %>" style="background-image: url('<%= u.image_url.to_s %>');"></div><% end %></div>
      
        </div>  
      <% end %>
    </div>

    <input type="hidden" id="hours_0_open" value="<%= printTimeFloat(@location.monday_open)%>">
    <input type="hidden" id="hours_0_close" value="<%= printTimeFloat(@location.monday_close)%>">
    <input type="hidden" id="hours_1_open" value="<%= printTimeFloat(@location.tuesday_open)%>">
    <input type="hidden" id="hours_1_close" value="<%= printTimeFloat(@location.tuesday_close)%>">
    <input type="hidden" id="hours_2_open" value="<%= printTimeFloat(@location.wednesday_open)%>">
    <input type="hidden" id="hours_2_close" value="<%= printTimeFloat(@location.wednesday_close)%>">
    <input type="hidden" id="hours_3_open" value="<%= printTimeFloat(@location.thursday_open)%>">
    <input type="hidden" id="hours_3_close" value="<%= printTimeFloat(@location.thursday_close)%>">
    <input type="hidden" id="hours_4_open" value="<%= printTimeFloat(@location.friday_open)%>">
    <input type="hidden" id="hours_4_close" value="<%= printTimeFloat(@location.friday_close)%>">
    <input type="hidden" id="hours_5_open" value="<%= printTimeFloat(@location.saturday_open)%>">
    <input type="hidden" id="hours_5_close" value="<%= printTimeFloat(@location.saturday_close)%>">
    <input type="hidden" id="hours_6_open" value="<%= printTimeFloat(@location.sunday_open)%>">
    <input type="hidden" id="hours_6_close" value="<%= printTimeFloat(@location.sunday_close)%>">

    <input type="hidden" name="is_manager" id="is_manager" value="<%= current_user.manager %>">

  </div>

app/views/schedules/index.html.erb
<div class="schedules_wrapper">
  <h2>View Schedules:</h2>

  <ul>
    <% @schedules.each do |s| %>
    <li class="schedule_list">
      <i class="calendar icon"></i>
      <span class="week_of_label">Week of</span>
      <br>
      <%= link_to s.week_of.to_formatted_s(:long_ordinal), schedule_path(s.week_of) %>
    </li>
    <% end %>
  </ul>

</div>

app/views/schedules/new.html.erb
<% @weekdays = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] %>
<div id="finished_employees">
  <div id="success_text">
    <h2>Schedule Saved.</h2>
    <p>This schedule has been posted to your employees.</p>
    <br><br><br>
    <p><%= link_to "Return to Control Panel", root_path %></p>
  </div>
</div>

<div id="get_week_and_location_backdrop">
  <div id="get_week_and_location_container">
    <h2>Create New Schedule
    <h4>What week should this schedule be for?</h4>
    <div class="ui selection dropdown">
      <input type="hidden" name="week_of_select" id="week_of_select">
      <div class="default text" style="width: 300px;">Select Date</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <div class="item" data-value="2014-5-19">Monday, May 19 - Sunday, May 25</div>
        <div class="item" data-value="2014-5-26">Monday, May 26 - Sunday, June 1</div>
        <div class="item" data-value="2014-6-2">Monday, June 2 - Sunday, June 8</div>
        <div class="item" data-value="2014-6-9">Monday, June 9 - Sunday, June 15</div>

      </div>
    </div>

    <h4>What location is this schedule for?</h4>
    <div class="ui selection dropdown">
      <input type="hidden" name="location_select" id="location_select">
      <div class="default text" style="width: 300px;">Select Location</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @locations.each do |l| %>
          <div class="item" data-value="<%= l.id %>"><%= l.name %></div>
        <% end %>


      </div>
    </div>

    <div id="starting_stats_error">
      Please select a week and location!
    </div>


    <div id="update_starting_button_container">
      <div class="ui green button" id="update_starting_stats">
        Create Schedule
      </div>
      <!-- <input type="button" id="update_starting_stats" value="Create schedule"> -->
    </div>
  </div>
</div>

<h2 id="schedule_header">Create New Schedule</h2>
<div id="make_new_schedule_container">
  <div id="side_panel">
    <h4>Add New Shift</h4>

    <div id="shift_slider_label">
      <strong>New Shift:</strong> <span id="start_label"></span> to <span id="end_label"></span>
    </div>
    <div id="shift_slider"></div>
    <input type="hidden" name="shift_start_time" id="shift_start_time" value="">
    <input type="hidden" name="shift_end_time" id="shift_end_time" value="">

    <div id="new_shift_days">
      <h4>Select Applicable Days:</h4>
      
      <div id="new_shift_checkbox_container">
        <% 7.times do |i| %>
        <div class="ui form">
          <div class="inline field">
            <div class="ui toggle checkbox">
              <input type="checkbox" id="day_<%= i %>" class="day_checkbox">
              <label><%= @weekdays[i] %></label>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div id="new_shift_checkbox_bulk">
        <div id="quick_select"><strong>Quick Select:</strong></div>
        <label><input type="radio" name="quickselect" id="day_all" class="day_radio" value="all">All</label>
        <label><input type="radio" name="quickselect" id="day_weekday" class="day_radio" value="weekdays">Weekdays</label>
        <label><input type="radio" name="quickselect" id="day_weekend" class="day_radio" value="weekend">Weekend</label>
        <label><input type="radio" name="quickselect" id="day_none" class="day_radio" value="none">None</label>



      </div>

    </div>

    <div class="ui labeled icon teal button" id="add_shift" style="width: 100%;">
      <i class="plus icon"></i>
      Add Shift
    </div>

    <div id="new_schedule_submit_container">
      <%= form_tag schedules_path, id: 'save_schedule_form' do %>

        <%= hidden_field_tag "week_of", "" %>
        <%= hidden_field_tag "location_id", "" %>
        <%= hidden_field_tag "open_hour", @earliest_open %>
        <%= hidden_field_tag "close_hour", @latest_close %>
        <%= hidden_field_tag "company_id", current_user.company.id %>
        <div class="ui labeled icon green button" id="save_schedule_button" style="width: 260px;">
          <i class="save icon"></i>
          Save Shifts
        </div>

      <% end %>
    </div>
    

    
  </div>


  <%= render "schedule" %>






  <div id="employees_roster_spacefiller"></div>
  <div id="employees_roster">
    <div id="save_employees_button_container">
      <%= form_tag shifts_path, id: 'save_shifts_form' do %>
        <div class="ui labeled icon green huge button" id="save_employees_button">
          <i class="save icon"></i>
          Save Schedule
        </div>
      <% end %>  
    </div>


    <div id="employee_container">
      <div id="title_n_tabs">
        <div id="tab_header" class="active">
          <h4>All Employees</h4>
        </div>
        <div id="tab_filter">
            <div class="ui left icon input">
              <input type="text" placeholder="Find an employee..." style="padding: 0.30em 1em;" id="name_filter">
              <i class="users icon" style="padding-top: 0.5em;"></i>
            </div>
        </div>

      </div>

      
      <% @users = @company.users %>
      <% @users.each do |user| %>
        <%=link_to employee_path(user), :class => "employee_avatar_box" do %><div class="employee_avatar" id="employee_<%= user.id %>" data-fname="<%= user.fname.downcase %>" data-lname="<%= user.lname.downcase %>" style="background-image: url('<%= user.image_url.to_s %>');">
          </div><% end %>
      <% end %>





<input type="hidden" id="page_id" value="new_schedule">







<div class="ui basic small modal" id="employee_detail_modal">
  <i class="close icon"></i>
  <div class="header" style="font-size: 3.5rem; margin-bottom: -30px;">
    <span id="modal_first_name"></span> <span id="modal_last_name"></span>
  </div>
  <div class="content">
    <div class="left" style="width: 20%;">
      <img src="" id="modal_avatar" style="width: 100%; border-radius: 20px;">
    </div>
    <div class="right">
      <div class="modal_role_container" style="margin-bottom: 25px; font-size: 1.5rem;">Role: <span id="modal_role"></span></div>
      <span class="modal_available" id="unavailability_header">Available for all shifts this week.</span>

      <div id="modal_una_holder" style="font-size: 0.75em;">

      </div>

    </div>
  </div>
  <div class="actions">
    <div class="ui green button">OK</div>
  </div>
</div>

app/views/schedules/show.html.erb
<% @weekdays = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] %>

<div id="show_schedule_container">
<!--   <div id="side_panel">
    <h4>Employee Info</h4>
  </div> -->
  <div class="button_next_week_container" style="text-align: left; margin-left: 68px; margin-right: 60px; position: relative; top: -40px;">
    <h2 style="color: #57C2B8; text-align: left;">Week of <%= @schedule.week_of %></h2>
  </div>
  <%= hidden_field_tag "open_hour", @earliest_open %>
  <%= hidden_field_tag "close_hour", @latest_close %>
  <%= render 'schedule' %>

</div>

<div class="navigation_arrow_buttons" style="margin-top: 15px;">
  <% if @next_week %>
    <%= link_to schedule_path(@next_week.week_of), id: "view_next_week", class: "ui right labeled icon button" do %>
      <i class="right arrow icon"></i>
      Next Week
    <% end %>
  <% end %>
  <% if @last_week %>
    <%= link_to schedule_path(@last_week.week_of), id: "view_last_week", class: "ui left labeled icon button" do %>
      <i class="left arrow icon"></i>
      Last Week
    <% end %>
  <% end %>
</div>

<div id="filler_div" style="position: relative; height: 75px;"></div>

<input type="hidden" id="page_id" value="show_schedule">