config/routes.rb
Rails.application.routes.draw do

  resources :employees, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :users do   
      resources :unavailabilities   
  end
  resources :schedules, only: [:index, :show, :new, :create]

  resources :shifts, only: [:create]

  get 'schedule/:id' => 'schedules#show'

  root 'users#index'

  get ':id/new' => 'companies#new_employee', as: "new_employee"

end

app/views/layouts/_employee_header.html.erb
<div class="emp_list_navbar">
  <table class="leftemp">
    <tr>
      <td class='titleheader'>Employee</td>
      <td class='titleheader'>
        Position
      </td>
    </tr>
  </table>
</div>

app/views/layouts/_employee_stats.html.erb
<div class="employee_container">
		<%= render 'users/allemployees' %>
</div>
<div class="employee_display">
		<%= render 'users/employee_details' %>
</div>

app/views/layouts/_navbar.html.erb
<nav class='top-bar'>
	<section class='big_logo'>
	  <%= link_to 'Schedulr', root_path %>
	</section>

  <section id='edit_my_profile'>
    <% if current_user && !current_user.manager %>

      <%= link_to "Change Availability", new_user_unavailability_path(current_user), class: "ui small teal button", id: "change_availability_button" %>

    <% end %>
  </section>
  <section id='check_my_schedule'>
    <div class="ui blue labeled icon top left pointing dropdown small button" id="view_schedule_button">
      <i class="calendar icon"></i>
      <span class="text">View Schedule</span>
      <div class="menu">
        <div class="item"><i class="edit icon"></i>Edit</div>
        <div class="item"><i class="delete icon"></i>Remove</div>
        <div class="item"><i class="hide icon"></i>Hide</div>
      </div>
    </div>
  </section>
  <section id='create_new_schedule'>
    <div class="ui animated fade button">
      <div class="visible content">
        <% if current_user && current_user.manager %>
          <%= button_to "Create a New Schedule", new_schedule_path, id: :create_new_schedule_button, :method => 'get' %>  
      </div>
    <div class='hidden content'>
      <%= link_to new_schedule_path, id: :create_new_schedule_button, :method => 'get' do %>
         <i class='calendar icon'></i>
      <% end %> 
    </div>
  </div>
  <% end %>
  </section>
	<section class='login_details'>
		<% if current_user %>
			<%= link_to current_user.email, edit_user_path(current_user), id: :myself %> | <%= link_to 'Log out', session_path(current_user), id: :logout, method: :delete %>
		<% else %>
      <div id="login_links">
        <%= link_to "Login", new_session_path, id: "show_login_form" %> or <%= link_to "Register", new_user_path %>
      </div>

      <div id="login_form">
        <div class='ui form'>
          <div class="inline fields">
            
            <div class="field">
              <%= form_tag sessions_url do  %>
              <%= text_field_tag :email, params[:email], placeholder: "Email Address" %>
            </div>
            <div class="field">
              <%= password_field_tag :password, placeholder: 'test', class: 'pwfield' %>
            </div>
            <div class='ui tiny vertical animated button'>
              <div class='visible content'>
                Log in
              </div>
              <div class='hidden content'>
                <%= image_submit_tag('rightarrow.png', class: 'rightarrow') %>
              </div>
            </div>
            <div class='ui tiny vertical animated button'>
              <div class='visible content'>
                Register
              </div>
              <div class='hidden content'>
                <%= link_to image_tag('rightarrow.png', class: 'rightarrowinvert'), new_user_path %>
              </div>
            </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>	
	</section>




</nav>

app/views/layouts/_navbar2.html.erb
<div class="navbar">
  <div class="main_symbol">
    <div id="bar1"></div>
    <div id="bar2"></div>
    <div id="bar3"></div>
  </div>

  <div class="main_logo">
    <%= link_to 'Schedulr', root_path %>
  </div>

  <% if current_user %>
    <div class="main_menu">
      <div class="ui dropdown icon" id="main_menu_button">
        <i class="reorder icon"></i>
        <div class="menu" id="nav_menu">
          <%= link_to schedules_path do %>
          <div class="item">
            <i class="calendar icon"></i>View Schedules
          </div>
          <% end %>
          <% if current_user && current_user.manager %>
            <%= link_to new_schedule_path do %>
              <div class="item">
                <i class="empty calendar icon"></i>Create New Schedule
              </div>
            <% end %>
          <% end %>
          <%= link_to edit_user_path(current_user) do %>
            <div class="item">
              <i class="user icon"></i>Edit Profile
            </div>
          <% end %>
          <% if current_user && !current_user.manager %>
            <%= link_to new_user_unavailability_path(current_user) do %>
              <div class="item">
                <i class="edit icon"></i>Edit Availability
              </div>
            <% end %>
          <% end %>
          <%= link_to session_path(current_user), method: :delete do %>
            <div class="item">
              <i class="off icon"></i>Log Off
            </div>
          <% end %>
          
        </div>
      </div>
    </div>
  <% else %>
    <div class="login_links">
      <%= link_to "Login", new_session_path, id: "show_login_form" %> or <%= link_to "Register", new_user_path %>
    </div>
    <%= form_tag sessions_url do  %>
      <div class="login_form">
        <div class="field">
          <div class="ui left labeled icon input">

            <%= email_field_tag :email, params[:email], id: "login_email_field", class: "login_field", placeholder: "Email Address" %>
            <i class="user icon" style="padding-top: 0.6rem;"></i>
            <div class="ui corner label">
              <i class="icon asterisk"></i>
            </div>
          </div>
        </div>
        <div class="field">
          <div class="ui left labeled icon input">
            <%= password_field_tag :password, nil, id: "login_password_field", class: "login_field" %>
            <i class="lock icon" style="padding-top: 0.6rem;"></i>
            <div class="ui corner label">
              <i class="icon asterisk"></i>
            </div>
          </div>
        </div>
        <%= submit_tag "Login", class: "ui blue submit button" %>
        <p class="login_register_link">- <%= link_to "Register a New Account", new_user_path %> -</p>
      </div>
    <% end %>
  <% end %>

</div>

app/views/layouts/_new_session.html.erb
<div class="new_login_session">
<h1>Log In!</h1>

<% if flash[:alert] %>
	<h2 style="color: red"><%= flash[:alert] %></h2>
<% end %>

<%= form_tag sessions_url do  %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>

  <div class="actions">
    <%= submit_tag "Log in" %>
  </div>  
<% end %>
</div>

app/views/layouts/_offdays.html.erb
<%= form_for [@user, @unavailabilities] do |f| %>

  <h2 class="ui left floated header">Days I can't work:</h2><br>
  

  <%= f.select(:day, options_for_select(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])) %>

  <div class='field'>
  <label>Start: </label>
   <%= f.time_select :duration_start, :minute_step =>15 %>
   </div>

  <div class='field'>
  <label>End: </label> 
   <%= f.time_select :duration_end, :minute_step =>15 %><br>
  <%= f.submit id: 'submit_unav', class: 'mini ui button' %>
  </div>
  <br>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>

  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script src="http://use.edgefonts.net/cabin.js"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/navbar2.html.erb' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/no_top_bar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>

  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script src="http://use.edgefonts.net/cabin.js"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>